# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend \
            ${LAYERDIR}/meta/*.bb"

BBFILE_COLLECTIONS += "meta-ettus-bsp-layer"
BBFILE_PATTERN_meta-ettus-bsp-layer = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-ettus-bsp-layer = "6"

LAYERSERIES_COMPAT_meta-ettus-bsp-layer = "scarthgap"

BINARYDIR = "${LAYERDIR}/binary"

BBFILES_DYNAMIC += " \
xilinx-tools:${LAYERDIR}/dynamic-layers/meta-xilinx-tools/recipes-*/*/*.bb \
xilinx-tools:${LAYERDIR}/dynamic-layers/meta-xilinx-tools/recipes-*/*/*.bbappend \
"
