parameters:
  - name: machines
    type: object
    default: {}
  - name: image
    type: string
    default: gnuradio-image
  - name: flash_image
    type: boolean
    default: true
  - name: image_ext
    type: string
    default: sdimg.bz2
  - name: tests
    type: object
    default:
    - test_power_on_off
    - test_linux
    - test_uhd
    - test_mender
    - test_salt
    - test_sound

jobs:
- job: 'test'
  timeoutInMinutes: 120
  strategy:
    matrix: ${{ parameters.machines }}

  variables:
    - group: meta-ettus-vars
    - name: labgrid-venv
      value: '$(Pipeline.Workspace)/labgrid-venv'
    - name: image
      value: ${{ parameters.image }}
    - name: image-ext
      value: ${{ parameters.image_ext }}
    - name: build_result
      value: $[ stageDependencies.build_meta_ettus.build.result ]
    - name: runTests
      value: true
    - name: lgConfigPath
      value: '$(Agent.TempDirectory)/lg-config.yml'

  pool:
    name: de-dre-lab
    demands:
    - Agent.OS -equals Linux
    - embedded-test -equals 1

  steps:
  - checkout: self
  - checkout: ettus-rts
  - checkout: labgrid
  - download: current
    artifact: $(deviceType)-images
    displayName: download artifacts from current
    condition: and(succeeded(), ne(variables.build_result, 'Skipped'), ${{ parameters.flash_image }})
  - script: |
      echo "###vso[task.setVariable variable=ImagePath]$(Agent.BuildDirectory)/$(deviceType)-images/$(image)-$(machine).$(image-ext)"
      echo "###vso[task.setVariable variable=MenderPath]$(Agent.BuildDirectory)/$(deviceType)-images/$(image)-$(machine).mender"
    displayName: set image path (from current)
    condition: and(succeeded(), ne(variables.build_result, 'Skipped'), ${{ parameters.flash_image }})
  - download: self
    artifact: $(deviceType)-images
    displayName: download artifacts from last run
    condition: and(succeeded(), eq(variables.build_result, 'Skipped'), ${{ parameters.flash_image }})
  - script: |
      echo "###vso[task.setVariable variable=ImagePath]$(Agent.BuildDirectory)/$(deviceType)-images/$(image)-$(machine).$(image-ext)"
      echo "###vso[task.setVariable variable=MenderPath]$(Agent.BuildDirectory)/$(deviceType)-images/$(image)-$(machine).mender"
    displayName: set image path (from last run)
    condition: and(succeeded(), eq(variables.build_result, 'Skipped'), ${{ parameters.flash_image }})
  - script: |
      for PKG in snmp libsnmp??; do
        apt-get download $PKG
        dpkg-deb -x $PKG*.deb .
      done
      PATH=$PATH:$PWD/usr/bin
      LD_LIBRARY_PATH=$PWD/usr/lib/x86_64-linux-gnu
      echo "###vso[task.setVariable variable=PATH]$PATH"
      echo "###vso[task.setVariable variable=LD_LIBRARY_PATH]$LD_LIBRARY_PATH"
    displayName: 'locally install snmp'
    condition: False
  - script: |
      python3 -m venv $(labgrid-venv)
      source $(labgrid-venv)/bin/activate
      pip install --upgrade pip
      pip install $(Build.SourcesDirectory)/meta-ettus-dev/contrib/test/usrp_emb2
    displayName: 'Setup labgrid-venv'

  - script: |
      source $(labgrid-venv)/bin/activate
      usrp-emb-update -s "$(uartSerial)" -t $(deviceType) write_config -o "$(lgConfigPath)"
    displayName: 'generate labgrid config'

  - script: |
      source $(labgrid-venv)/bin/activate
      usrp-emb-update -s "$(uartSerial)" -t $(deviceType) update $(ImagePath)
      rc=$?
      if [ $rc != 0 ]; then
        echo "###vso[task.setVariable variable=runTests]false"
      fi
      exit $rc
    displayName: flash image
    condition: and(succeeded(), ${{ parameters.flash_image }})

  - ${{ each test in parameters.tests }}:
    - script: |
        source $(labgrid-venv)/bin/activate
        pip install -r $(Build.SourcesDirectory)/ettus-rts/labgrid/tests/requirements.txt
        export PYTEST_ADDOPTS="--color=yes"
        if [ "${{ test }}" = "test_mender" ]; then
          additional_args="--mender=$(MenderPath)"
        else
          additional_args=""
        fi
        pytest --junitxml=$(Common.TestResultsDirectory)/${{ test }}.xml --lg-env $(lgConfigPath) $(Build.SourcesDirectory)/ettus-rts/labgrid/tests/${{ test }}.py -vv ${additional_args}
      displayName: run ${{ test }}
      condition: and(eq(variables.runTests, 'true'), not(canceled()))

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/*.xml'
      testRunTitle: 'Embedded Tests $(System.JobName)'
      searchFolder: '$(Common.TestResultsDirectory)'
    condition: eq(variables.runTests, 'true')
