parameters:
  - name: machines
    type: object
    default: []
  - name: upload_packages_to_fileserver
    type: boolean
    default: false
  - name: build_sdk
    type: boolean
    default: false
  - name: create_sbom
    type: boolean
    default: true
  - name: ccache
    type: boolean
    default: false
  - name: cache_sstate
    type: boolean
    default: true
  - name: cache_downloads
    type: boolean
    default: true
  - name: include_internal
    type: boolean
    default: false
  - name: auto_conf
    type: string
    default: ""
  - name: load_ssh_key
    type: boolean
    default: true
  - name: prebuild_steps
    type: stepList
    default:
      - script: env
      - script: ls -lsa $(Agent.BuildDirectory)
  - name: postbuild_steps
    type: stepList
    default:
      - script: env
  - name: use_custom_mender_prefix
    type: boolean
    default: false
  - name: custom_mender_prefix
    type: string
    default: 'meta-ettus-fs'
  - name: run_from_external_repo
    type: boolean
    default: False
  - name: kas_subdirectory
    type: string
    default: 'configs-mender'
  - name: build_default_targets
    type: boolean
    default: True
  - name: pre_targets
    type: string
    default: ""
  - name: post_targets
    type: string
    default: "uhd:do_run_tests"
  - name: cache_base_name
    type: string
    default: "scarthgap"
  - name: sbom_cve_check
    type: boolean
    default: false
  - name: sbom_project_os_id
    type: string
    default: "scarthgap"

jobs:
  - job: get_usrp_kas_docker_image
    displayName: Get usrp-kas docker image
    pool:
      name: Drivers-NIBuildFarm-RFMIBuild
      demands: sh
    steps:
      - checkout: none
      - download: usrp-kas-pipeline
        artifact: 'usrp-kas-docker-image'
        displayName: Download image info
      - script: |
          export USRP_KAS_DOCKER_IMAGE=$(cat $(Pipeline.Workspace)/usrp-kas-pipeline/usrp-kas-docker-image/docker_image)
          echo $USRP_KAS_DOCKER_IMAGE
          echo "###vso[task.setVariable variable=USRP_KAS_DOCKER_IMAGE;isOutput=true]$USRP_KAS_DOCKER_IMAGE"
        name: dockerVars
        displayName: Set output variables

  - job: build
    dependsOn: get_usrp_kas_docker_image
    timeoutInMinutes: 600
    cancelTimeoutInMinutes: 10
    strategy:
      matrix:
        ${{ each machine in parameters.machines }}:
          ${{ machine }}:
            machineName: ${{ machine }}
            # ${{ if eq(machine, 'e320') }}:
            #   pre_targets: mc:ni-neon-ec:chromium-ec ${{ parameters.pre_targets }}
            ${{ if length(trim(parameters.pre_targets)) }}:
              pre_targets: ${{ parameters.pre_targets }}
            ${{ else }}:
              pre_targets: --parse-only
            ${{ if length(trim(parameters.post_targets)) }}:
              post_targets: ${{ parameters.post_targets }}
            ${{ else }}:
              post_targets: --parse-only
    pool:
      name: Drivers-NIBuildFarm-RFMIBuild
      demands:
        - docker
        - Agent.OS -equals Linux

    variables:
      - group: meta-ettus-vars

      - name: USRP_KAS_DOCKER_IMAGE
        value: $[ dependencies.get_usrp_kas_docker_image.outputs['dockerVars.USRP_KAS_DOCKER_IMAGE'] ]
      - name: package_version
        ${{ if parameters.use_custom_mender_prefix }}:
          value: '${{ parameters.custom_mender_prefix }}'
        ${{ if not(parameters.use_custom_mender_prefix) }}:
          value: '$(Build.BuildNumber)'
      - name: MENDER_ARTIFACT_NAME
        ${{ if parameters.use_custom_mender_prefix }}:
          value: '${{ parameters.custom_mender_prefix }}_$(machineName)'
        ${{ if not(parameters.use_custom_mender_prefix) }}:
          value: '$(Build.BuildNumber)_$(machineName)'
      - ${{ if parameters.cache_downloads }}:
        - name: DL_DIR
          value: '$(Agent.BuildDirectory)/downloads'
      - ${{ if parameters.cache_sstate }}:
        - name: SSTATE_DIR
          value: '$(Agent.BuildDirectory)/sstate-cache'
      - ${{ if parameters.ccache }}:
        - name: CCACHE_DIR
          value: '$(Agent.BuildDirectory)/ccache'

    container:
      image: $(USRP_KAS_DOCKER_IMAGE)
      options: -e NO_PROXY="" --security-opt seccomp=unconfined
      endpoint: 'rnd-docker-niartifacts-pre-readonly'

    steps:
      - ${{ if parameters.run_from_external_repo }}:
        - checkout: self
          persistCredentials: true
        - checkout: meta-ettus
          persistCredentials: true
      - ${{ else }}:
        - checkout: self
          persistCredentials: true

      - ${{ if parameters.load_ssh_key }}:
        - task: InstallSSHKey@0
          inputs:
            sshKeySecureFile: 'id_rsa.meta-ettus'
            knownHostsEntry: 'github.com,192.30.253.113 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk='
            sshPublicKey: $(ettus_ssh_pubkey) # from meta-ettus-vars

      - script: |
          CacheTimestamp=$(date "+%Yw%U")
          echo "CacheTimestamp=$CacheTimestamp"
          echo "###vso[task.setVariable variable=CacheTimestamp]$CacheTimestamp"
        displayName: set CacheTimestamp

      - ${{ if parameters.cache_downloads }}:
        - task: Cache@2
          displayName: "Cache downloads"
          inputs:
            key: '"${{ parameters.cache_base_name }}" | "downloads" | "$(CacheTimestamp)"'
            restoreKeys: '"${{ parameters.cache_base_name }}" | "downloads"'
            path: $(DL_DIR)

      - ${{ if parameters.cache_sstate }}:
        - task: Cache@2
          displayName: "Cache sstate"
          inputs:
            key: '"${{ parameters.cache_base_name }}" | "sstate" | "$(machineName)" | "$(CacheTimestamp)"'
            restoreKeys: '"${{ parameters.cache_base_name }}" | "sstate" | "$(machineName)"'
            path: $(SSTATE_DIR)

      - ${{ if parameters.ccache }}:
        - task: Cache@2
          displayName: "Cache ccache"
          inputs:
            key: '"${{ parameters.cache_base_name }}" | "ccache" | "$(machineName)" | "$(CacheTimestamp)"'
            restoreKeys: '"${{ parameters.cache_base_name }}" | "ccache" | "$(machineName)"'
            path: $(CCACHE_DIR)

      - script: |
          set -e
          wget http://http.us.debian.org/debian/pool/main/n/ncurses/libtinfo5_6.4-4_amd64.deb
          echo "SHA256 (libtinfo5_6.4-4_amd64.deb) = dd347f794e651039e7b4c391f86c674fed7f415b3dca6b0937beb0d470f09c1a" | sha256sum -c -
          sudo dpkg -i libtinfo5_6.4-4_amd64.deb
        displayName: install libtinfo5

      - script: |
          rm $(Agent.BuildDirectory)/site.conf
          touch $(Agent.BuildDirectory)/site.conf
        displayName: create site.conf

      - script: |
          cat <<EOF >>$(Agent.BuildDirectory)/site.conf
          TESTRESULTS_DIR = "$(Common.TestResultsDirectory)"
          EOF
        displayName: Pass test directory var

      - script: |
          cat <<EOF >>$(Agent.BuildDirectory)/site.conf
          INHERIT += "archiver"
          ARCHIVER_MODE[src] = "original"
          EOF
        displayName: Enable archiver to generate sources

      - script: |
          set -e
          if [[ -z "${PIP_INDEX_URL:-}" ]]; then
            echo "Error: The variable pip_index_url is not set, its value was '$PIP_INDEX_URL'"
            echo "It must be set as a variable in pipeline variable group meta-ettus-vars and point to the correct PyPI server"
            exit 1
          fi
          set +e
          cat <<EOF >>$(Agent.BuildDirectory)/site.conf
          PREMIRRORS:prepend = "https://files.pythonhosted.org/.* $PIP_INDEX_URL/ \n"
          EOF
          cat $(Agent.BuildDirectory)/site.conf
        displayName: Define global pypi mirror for bitbake
        
      - ${{ if parameters.create_sbom }}:
        - script: |
            if [ "${{ parameters.sbom_cve_check }}" = "True" ]; then
              ALCHEMY_CREATE_CVE_CHECK="1"
            else
              ALCHEMY_CREATE_CVE_CHECK="0"
            fi
            cat <<EOF >>$(Agent.BuildDirectory)/site.conf
            ALCHEMY_CREATE_SBOM = "1"
            ALCHEMY_CREATE_CVE_CHECK = "$ALCHEMY_CREATE_CVE_CHECK"
            # Map MG/RH cpld license name to valid, common
            # SPDX-License-Identifier (for details see US 3116752)
            SPDXLICENSEMAP[Firmware-GPLv2] = "GPL-2.0-only"
            EOF
            cat $(Agent.BuildDirectory)/site.conf
          displayName: Enable SBOM (SPDX) generation

      - ${{ if parameters.ccache }}:
        - script: |
            mkdir -p $CCACHE_DIR

            cat <<EOF >>$(Agent.BuildDirectory)/site.conf
            INHERIT += "ccache"
            CCACHE_TOP_DIR = "$CCACHE_DIR"
            EOF
          displayName: "Setup ccache"

      - ${{ parameters.prebuild_steps }}

      - script: |
          KAS_BASE_PATH=$(find $(Pipeline.Workspace) -wholename '*/kas/include' -exec realpath {} \; | head | sed 's;/include;;')
          echo $KAS_BASE_PATH
          echo "###vso[task.setVariable variable=KAS_BASE_PATH]"$KAS_BASE_PATH
        displayName: Find kas base path

      - script: |
          git -C $KAS_BASE_PATH/.. log -1
          REPRODUCIBLE_TIMESTAMP_ROOTFS=$(git -C $KAS_BASE_PATH/.. log -1 --pretty=%ct 2>/dev/null)
          echo REPRODUCIBLE_TIMESTAMP_ROOTFS=$REPRODUCIBLE_TIMESTAMP_ROOTFS
          cat <<EOF >>$(Agent.BuildDirectory)/site.conf
          REPRODUCIBLE_TIMESTAMP_ROOTFS = "$REPRODUCIBLE_TIMESTAMP_ROOTFS"
          EOF
        displayName: "Set reproducible timestamp for rootfs"

      - template: kas_build.yml
        parameters:
          kas_config:
            - $KAS_BASE_PATH/${{ parameters.kas_subdirectory }}/$(machineName).yml
            - ${{ if eq(parameters.include_internal, true) }}:
              - $KAS_BASE_PATH/internal.yml
          auto_conf: ${{ parameters.auto_conf }}
          site_conf: $(Agent.BuildDirectory)/site.conf
          build_package_feed: True
          build_sdk: ${{ parameters.build_sdk }}
          build_default_targets: ${{ parameters.build_default_targets }}

      - script: |
          rm -rf ./images
          mkdir images

          # boot binary
          cp -v $KAS_DEPLOY_DIR_IMAGE/boot.bin images/

          # boot binary input files
          SRCDIR="$KAS_DEPLOY_DIR_IMAGE/boot.bin-extracted"
          DESTDIR="images/boot.bin-extracted"
          mkdir -p $DESTDIR
          for FILE in $SRCDIR/*.elf $SRCDIR/*.dtb $SRCDIR/*.bit $SRCDIR/*.bif; do
            cp -v $FILE $DESTDIR/
          done

          # main image
          find $KAS_DEPLOY_DIR -type l -name '*.wic.*' -exec cp {} images \;
          find $KAS_DEPLOY_DIR -type l -name '*.sdimg.*' -exec cp {} images \;
          find $KAS_DEPLOY_DIR -type l -name '*.tar.*' -exec cp {} images \;
          find $KAS_DEPLOY_DIR -type l -name '*.manifest' -exec cp {} images \;

          # spdx sbom
          find $KAS_DEPLOY_DIR/images -type l -name '*.spdx*.json' -exec cp {} images \;
          # spdx archive also include in '*.tar.*' wildcard for main image
          find $KAS_DEPLOY_DIR/images -type l -name '*.spdx.tar.zst' -exec cp {} images \;

          # cve summary in text file format
          find $KAS_DEPLOY_DIR/images -type l -name '*.cve' -exec cp {} images \;
          # cve summary in json file format, need to use wildcard because base name is not fixed,
          # will include *.spdx*.json files another time
          find $KAS_DEPLOY_DIR/images -type l -name '*.json' -exec cp {} images \;
          # cve
          mkdir -p images/cve
          find $KAS_DEPLOY_DIR/cve -exec cp {} images/cve \;

          # mender image
          find $KAS_DEPLOY_DIR -type l -name "*.mender" -exec cp {} images \;

          # microcontroller firmware
          find $KAS_DEPLOY_DIR -type f -name "ec-*-rev*.bin" -exec cp {} images \;

          # x4xx specific
          find $KAS_DEPLOY_DIR -type l -name "u-boot-jtag-files.zip" -exec cp {} images \;
          find $KAS_DEPLOY_DIR -type l -name "fitImage-manufacturing-image*" -exec cp {} images/fitImage-manufacturing \;

          find images
          true
        workingDirectory: $(Agent.BuildDirectory)
        displayName: Aggregate images

      - script: |
          rm -rf ./packages
          mkdir ./packages
          cd ./packages
          $KAS_BASE_PATH/../contrib/create_packages.sh $(machineName) $(package_version) gnuradio-image $KAS_DEPLOY_DIR
        workingDirectory: $(Agent.BuildDirectory)
        displayName: Create packages

      - publish: $(Agent.BuildDirectory)/packages
        artifact: "$(machineName)-packages"
        displayName: Publish packages

      - task: CopyFilesOverSSH@0
        inputs:
          sshEndpoint: ettus-fileserver
          sourceFolder: $(Agent.BuildDirectory)/packages
          targetFolder: "~/fromPipelines/$(Build.DefinitionName)/$(Build.BuildNumber)/$(machineName)"
        condition: and(succeeded(), ${{ parameters.upload_packages_to_fileserver }})
        displayName: Copy packages to fileserver

      - publish: $(Agent.BuildDirectory)/images
        artifact: "$(machineName)-images"
        displayName: Publish images

      - publish: $(KAS_DEPLOY_DIR)/ipk
        artifact: "$(machineName)-ipks"
        displayName: Publish ipks

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: cTest
          testResultsFiles: $(Common.TestResultsDirectory)/uhd/Testing/**/Test.xml
          failTaskOnFailedTests: false
          testRunTitle: uhd ctest meta-ettus-$(machineName)
        displayName: Publish uhd meta-ettus-$(machineName) ctest results

      - ${{ parameters.postbuild_steps }}

      - script: |
          rm -rf $(Agent.BuildDirectory)/build
          rm -rf $(Agent.BuildDirectory)/images
          rm -rf $(Agent.BuildDirectory)/packages
          rm -rf $(Agent.BuildDirectory)/logs
          rm -f $(Agent.BuildDirectory)/logs.tar*
          rm -f $(Agent.BuildDirectory)/site.conf
        displayName: Cleanup
        condition: always()

  - ${{ if parameters.create_sbom }}:
    - job: process_sboms
      dependsOn: build
      strategy:
        matrix:
          ${{ each machine in parameters.machines }}:
            ${{ machine }}:
              machineName: ${{ machine }}

      pool:
        name: Drivers-NIBuildFarm-RFMIBuild
        demands:
          - Agent.OS -equals Linux

      variables:
        - group: meta-ettus-vars

      steps:
        - template: steps-sbom-convert-spdx.yml
          parameters:
            artifact_name: '$(machineName)-images'
            release_build: ${{ parameters.upload_packages_to_fileserver }}
            sbom_project_base_name: 'usrp-${{ parameters.sbom_project_os_id }}'
            ${{ if parameters.run_from_external_repo }}:
              repo_name: meta-ettus
            ${{ else }}:
              repo_name: self