#!/usr/bin/env python3
"""
This script installs all IPK files in a directory to the device under test.
It copies the files to the device in a directory named /home/root/ipk, and
runs opkg to install the packages.

Usage:
./install_packages -s <ipk_dir> -c <config_file> -t <device_type>
"""
import sys
import subprocess
import glob
from utils import get_config
from utils import Ssh

def main(argv):
    ssh = Ssh('root', config['targetip'])

    print("\nStep 1: create directory for ipk files", flush=True)
    ipk_dir = '~/ipk'
    ssh.exec(['if [ -d {d} ]; then rm -rf {d}; fi'.format(d=ipk_dir)])
    ssh.exec('mkdir {d}'.format(d=ipk_dir))

    print("\nStep 2: copy ipk files", flush=True)
    src_dir = config['sourcedir']
    files = glob.glob('{src}/*.ipk'.format(src=src_dir))
    for file in files:
        ssh.copy_to(file, ipk_dir)

    print("\nStep 3: install packages", flush=True)
    ssh.exec(['opkg', 'install', '--force_reinstall', '--force_depends','{d}/*.ipk'.format(d=ipk_dir)])


if __name__ == "__main__":
    config = get_config(sys.argv)
    main(config)
