#!/usr/bin/env python3

import sys
import subprocess
from utils import get_config

def main(argv):
    mountpoint = config["nfsroot"]

    print("mounting {}".format(mountpoint))

    output = subprocess.run(["sudo", "systemctl", "start", "nfs-kernel-server"])
    output = subprocess.run(["mount", mountpoint])
    output = subprocess.run(["sudo", "rm", "{}/etc/resolv.conf".format(mountpoint)])
    output = subprocess.run(["sudo", "ln", "-s", "/proc/net/pnp", "{}/etc/resolv.conf".format(mountpoint)])

if __name__ == "__main__":
    config = get_config(sys.argv)
    main(config)
