#!/usr/bin/env python3

import sys
import subprocess
from utils import get_config
from utils import Ssh

def main(config):
    ssh = Ssh('root', config['targetip'])

    print("\nStep 2: delete old test directory")
    ssh.exec(['rm -rf {dst} && mkdir -p {dst}'.format(dst=config['test_dst_folder'])])

    print("\nStep 3: copy test files")
    ssh.copy_to('{src}/{tests}'.format(src=config['test_src_folder'], tests=config['tests_folder']),
            config['test_dst_folder'])

    print("\nStep 4: run test", flush=True)
    ret = ssh.unchecked_exec(['pip3 install {deps} && '.format(deps=config['tests_deps']),
        'cd {dst}/{tests} && {cmd}'.format( dst=config['test_dst_folder'],
        tests=config['tests_folder'], cmd=config['tests_command'])], stderr=subprocess.STDOUT)

    print("\nStep 5: copy test results", flush=True)
    ssh.copy(config['test_dst_folder'], '.')

    sys.exit(ret)

if __name__ == "__main__":
    config = get_config(sys.argv)
    main(config)
