#!/usr/bin/env python3

import sys
from utils import get_config
from utils import Ssh

def main(config):
    ssh = Ssh('root', config['targetip'])

    print("\nStep 2: delete old test directory")
    ssh.exec("rm -rf {dst} && mkdir -p {dst}".format(dst=config['mpm_test_folder']))

    print("\nStep 3: run tests", flush=True)
    ret = ssh.unchecked_exec(['cd', config['mpm_test_folder'], ';',
        'python3', '/usr/lib/usrp_mpm/tests/run_unit_tests.py', '-x', 'x4xx'])

    print("\nStep 4: copy results", flush=True)
    ssh.copy(config['mpm_test_folder'], '.')

    sys.exit(ret)

if __name__ == "__main__":
    config = get_config(sys.argv)
    main(config)
