#!/usr/bin/env python3

import sys
import subprocess
from utils import get_config

def main(config):
    mountpoint = config["nfsroot"]

    print("unmounting {}".format(mountpoint))

    output = subprocess.run(["sudo", "systemctl", "restart", "nfs-kernel-server"])
    output = subprocess.run(["umount", mountpoint])

if __name__ == "__main__":
    config = get_config(sys.argv)
    main(config)
