# no CI triggers
trigger: none

# no PR triggers
pr: none

variables:
  UHDForHostArtifactName: 'qemux86_64-ipks'
  ScriptDir: '$(Agent.BuildDirectory)/meta-ettus-dev/contrib/test'
  ConfigFile: '$(Agent.WorkFolder)/config.conf'
  ImagesDirectory: '$(Agent.WorkFolder)/images'
  IpkDir: '$(Agent.BuildDirectory)/x4xx-uhddev-oe-build-artifacts/x4xx-ipks/aarch64'

# pipeline triggers
resources:
  repositories:
  - repository: EttusRTS
    type: github
    endpoint: EttusResearch
    name: EttusResearch/ettus-rts
    ref: $(EttusRtsBranch)
  pipelines:
  - pipeline: usrp-filesystem-artifacts
    source: 'usrp-filesystem'
    project: DevCentral
    branch: zeus-ci
  - pipeline: x4xx-uhddev-oe-build-artifacts
    source: 'x4xx-uhddev-oe-build'
    project: DevCentral
    branch: master
    trigger:
      branches:
        include:
        - master
  - pipeline: x4xx-uhddev-oe-for-host-artifacts
    source: 'x4xx-uhddev-oe-for-host'
    project: DevCentral
    branch: master
    trigger:
      branches:
        include:
        - master
  - pipeline: x4xx-gnuradio-oe-for-host-artifacts
    source: 'x4xx-gnuradio-oe-for-host'
    project: DevCentral
    branch: master

pool:
  name: de-dre-lab
  demands:
  - AtsConfig -equals $(AtsConfig)

jobs:

- template: templates/job_x4xx_device_test.yml
