trigger:
  branches:
    include:
      - 'zeus-ci'
pr:
  branches:
    include:
      - 'zeus-ci'
      - '*/zeus/*'

schedules:
  - cron: "19 10 * * *"
    displayName: 'Daily build'
    branches:
      include:
        - 'zeus-ci'
    always: true

parameters:
  - name: release_build
    displayName: Build for release (disables caching, publishes archives)
    type: boolean
    default: false
  - name: upload_packages_to_fileserver
    displayName: "Upload packages to fileserver"
    type: boolean
    default: false
  - name: use_custom_mender_prefix
    type: boolean
    default: false
  - name: custom_mender_prefix
    type: string
    default: 'meta-ettus-fs'
  - name: build_sdk
    displayName: Build SDK
    type: boolean
    default: false
  - name: cache_sstate
    displayName: Use pipeline caching for sstate-cache
    type: boolean
    default: true
  - name: cache_downloads
    displayName: Use pipeline caching for downloads
    type: boolean
    default: false
  - name: ext_linux
    displayName: Override linux source
    type: boolean
    default: false
  - name: build_e310_sg1
    displayName: Build e310_sg1
    type: boolean
    default: true
  - name: build_e310_sg3
    displayName: Build e310_sg3
    type: boolean
    default: true
  - name: build_e320
    displayName: Build e320
    type: boolean
    default: true
  - name: build_n3xx
    displayName: Build n3xx
    type: boolean
    default: true
  - name: build_x4xx
    displayName: Build x4xx
    type: boolean
    default: true

resources:
  pipelines:
    - pipeline: usrp-kas-pipeline
      source: 'usrp-kas'
  repositories:
    - repository: linuxdev
      type: github
      name: EttusResearch/linuxdev
      ref: refs/heads/usrp-v5.10
      endpoint: EttusResearch

variables:
  - name: AUTO_CONF
    value: $(Agent.BuildDirectory)/auto.conf

jobs:
  - template: templates/job_build_filesystem.yml
    parameters:
      upload_packages_to_fileserver: ${{ parameters.upload_packages_to_fileserver }}
      build_sdk: ${{ parameters.build_sdk }}
      cache_sstate: ${{ and(parameters.cache_sstate, not(parameters.release_build)) }}
      cache_downloads: ${{ and(parameters.cache_downloads, not(parameters.release_build)) }}
      use_custom_mender_prefix: ${{ parameters.use_custom_mender_prefix }}
      custom_mender_prefix: ${{ parameters.custom_mender_prefix }}
      machines:
        - ${{ if parameters.build_e310_sg1 }}:
          - e310_sg1
        - ${{ if parameters.build_e310_sg3 }}:
          - e310_sg3
        - ${{ if parameters.build_e320 }}:
          - e320
        - ${{ if parameters.build_n3xx }}:
          - n3xx
        - ${{ if parameters.build_x4xx }}:
          - x4xx
      auto_conf: $AUTO_CONF
      prebuild_steps:
        - ${{ if parameters.ext_linux }}:
          - script: |
              rm $AUTO_CONF
              cat <<EOF >>$AUTO_CONF
              PREFERRED_PROVIDER_virtual/kernel = "linux-usrp"
              PREFERRED_VERSION_linux-yocto = "5.10%"
              KBUILD_DEFCONFIG = "usrp_defconfig"
              EOF
          - template: templates/oe_localconf_externalsrc.yml
            parameters:
              conf_file: $AUTO_CONF
              repository: linuxdev
              packages:
                - linux-usrp
