trigger:
  - zeus-ci

pr:
  branches:
    include:
      - zeus-ci

schedules:
  - cron: "0 19 * * *"
    displayName: 'Daily build'
    branches:
      include:
        - zeus-ci

parameters:
  - name: cache_sstate
    displayName: Use pipeline caching for sstate-cache
    type: boolean
    default: true

variables:
  - name: AUTO_CONF
    value: $(Agent.BuildDirectory)/auto.conf

resources:
  pipelines:
    - pipeline: usrp-kas-pipeline
      source: 'usrp-kas'
jobs:
  - template: templates/job_build_package.yml
    parameters:
      cache_sstate: ${{ parameters.cache_sstate }}
      include_internal: true
      auto_conf: $AUTO_CONF
      machines:
        - x4xx
      targets:
        - libniusrp2:do_package_write_ipk
        - niusrp2-bitfiles:do_package_write_ipk
        - x4xx-pyrats-bitfiles:do_package_write_ipk
