# no CI triggers
trigger: none

# no PR triggers
pr: none

variables:
  ScriptDir: '$(Build.SourcesDirectory)/contrib/test'
  ConfigFile: '$(Agent.WorkFolder)/config.conf'
  IpkDir: '$(Agent.BuildDirectory)/x4xx-filesystem-artifacts/$(machineName)-ipks/aarch64'
  USRP_EMB_FTDI_SERIAL: '2516351FE64E' # In use as of February 2021
  USRP_EMB_IMAGE_PATH: '$(Agent.BuildDirectory)/usrp-filesystem-artifacts/$(machineName)-images/'

# pipeline triggers
resources:
  pipelines:
  - pipeline: usrp-filesystem-artifacts
    source: 'usrp-filesystem'
    branch: zeus-ci
    trigger:
      # workaround if no additional branch filter is specified
      enabled: True
  - pipeline: x4xx-filesystem-artifacts
    source: 'x4xx-filesystem'
    branch: zeus-ci

pool:
  demands:
  - openembedded-test -equals x4xx

parameters:
  - name: mender_update
    displayName: Perform Mender update instead of flashing
    default: false
    type: boolean

jobs:
- job: 'test'
  timeoutInMinutes: 120
  strategy:
    matrix:
      x4xx:
        machineName: x4xx

  steps:
  - checkout: self

  - script: |
      rm -rf x4xx-filesystem-artifacts
      rm -rf usrp-filesystem-artifacts
    displayName: Cleanup from prior run
    workingDirectory: $(Agent.BuildDirectory)

  - download: usrp-filesystem-artifacts
    artifact: $(machineName)-images

  - download: x4xx-filesystem-artifacts
    artifact: $(machineName)-ipks

  - script: |
      cd $USRP_EMB_IMAGE_PATH
      unzip -o *.zip
    displayName: Extract any zip archives

  - template: templates/usrp_emb_setup.yml
  - ${{ if parameters.mender_update }}:
    - template: templates/usrp_emb_mender_update.yml
  - ${{ if not(parameters.mender_update) }}:
    - template: templates/usrp_emb_flash.yml
  - template: templates/usrp_emb_run_embedded_tests.yml
  - template: templates/usrp_emb_boot.yml
  - template: templates/steps_run_test.yml
  - script: $(ScriptDir)/install_packages -t $(machineName) -c $(ConfigFile) -s '$(IpkDir)'
    displayName: 'Install IPK files'
    workingDirectory: $(Agent.BuildDirectory)
  - template: templates/steps_run_rio_test.yml
  - template: templates/steps_run_mpm_test.yml
  - template: templates/steps_run_bist.yml
  - template: templates/steps_run_usrp2_c_test.yml
  - template: templates/usrp_emb_run_mender_tests.yml
