# no CI triggers
trigger: none

pr:
  branches:
    include:
      - titanium-zeus
  paths:
    include:
      - .ci
      - contrib/test

variables:
  ScriptDir: '$(Build.SourcesDirectory)/contrib/test'
  ConfigFile: '$(Agent.WorkFolder)/config.conf'
  ImageUrlFile: '$(Agent.BuildDirectory)/x4xx-filesystem-artifacts/$(System.JobName)-urls/filesystem-image.url'
  ImagesDirectory: '$(Agent.WorkFolder)/images'
  IpkDir: '$(Agent.BuildDirectory)/x4xx-uhddev-oe-build-artifacts/IPK files/aarch64'

# pipeline triggers
resources:
  pipelines:
  - pipeline: x4xx-filesystem-artifacts
    source: 'x4xx-filesystem'
    branch: titanium-zeus
  - pipeline: x4xx-uhddev-oe-build-artifacts
    source: 'x4xx-uhddev-oe-build'
    branch: titanium-master
    trigger:
      branches:
        exclude:
        - master

pool:
  name: de-dre-lab
  demands:
  - openembedded-test -equals $(System.JobName)

jobs:
- job: 'test'
  strategy:
    matrix: $[ variables.Devices ]

  workspace:
    clean: all

  steps:
  - checkout: self

  - download: x4xx-uhddev-oe-build-artifacts
    artifact: 'IPK files'
    displayName: 'Download IPK files'

  - download: x4xx-filesystem-artifacts
    artifact: $(System.JobName)-urls
    condition: not(variables['ImageUrl'])
    displayName: 'Get location of filesystem'

  - template: templates/steps_load_image.yml
  - template: templates/steps_mount_image.yml
  - template: templates/steps_run_boot.yml

  - script: $(ScriptDir)/install_packages -t $(System.JobName) -c $(ConfigFile) -s '$(IpkDir)'
    displayName: 'Install IPK files'
    workingDirectory: $(Agent.BuildDirectory)

  - template: templates/steps_run_mpm_test.yml
  - template: templates/steps_run_poweroff.yml
  - template: templates/steps_unmount_image.yml
