# no CI triggers
trigger: none

pr:
  branches:
    include:
      - zeus-ci
  paths:
    include:
      - .ci
      - contrib/test

variables:
  ScriptDir: '$(Build.SourcesDirectory)/contrib/test'
  ConfigFile: '$(Agent.WorkFolder)/config.conf'
  ImagesDirectory: '$(Agent.WorkFolder)/images'
  UHDForHostArtifactName: 'qemux86_64-ipks'

# pipeline triggers
resources:
  pipelines:
  - pipeline: usrp-filesystem-artifacts
    source: 'usrp-filesystem'
    branch: zeus-ci
    trigger:
      # workaround if no additional branch filter is specified
      enabled: False
  - pipeline: 'x4xx-uhddev-oe-for-host-artifacts'
    source: 'x4xx-uhddev-oe-for-host'
    branch: master
    trigger:
      # workaround if no additional branch filter is specified
      enabled: True
pool:
  demands:
  - openembedded-test -equals $(System.JobName)

jobs:
- job: 'test'
  strategy:
    matrix: $[ variables.Devices ]

  workspace:
    clean: all

  steps:
  - checkout: self

  - template: templates/steps_generate_opkg_conf.yml
    parameters:
      pipeline: x4xx-uhddev-oe-for-host-artifacts
      artifact: '$(UHDForHostArtifactName)'
      conf_file: $(Agent.BuildDirectory)/opkg-uhddev.conf

  # - template: templates/steps_load_image.yml
  - template: templates/steps_mount_image.yml
  - template: templates/steps_run_boot.yml

  - script: |
      sleep 30
    displayName: 'Wait for device initialization'

  - template: templates/steps_update_bitfile.yml
  # - template: templates/steps_run_mpm_test.yml
  - template: templates/steps_run_remote_test.yml
  - template: templates/steps_run_poweroff.yml
  - template: templates/steps_unmount_image.yml
