# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-sulfur-layer"
BBFILE_PATTERN_meta-sulfur-layer = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-sulfur-layer = "6"

LAYERSERIES_COMPAT_meta-sulfur-layer = "scarthgap"

# Map MG/RH cpld license name to valid, common
# SPDX-License-Identifier (for details see US 3116752)
SPDXLICENSEMAP[Firmware-GPLv2] = "GPL-2.0-only"
