#@TYPE: Machine
#@Name: Ettus Research Neon.
#@DESCRIPTION: Machine configuration for the Ettus Research Neon Rev2 Software Radio.

require conf/machine/ni-neon.inc

MACHINEOVERRIDES .= ":ni-neon-rev2"

DTB_FILES = "zynq-ni-neon-rev1.dtb"
KERNEL_DEVICETREE = '${@' '.join('xilinx/%s' % d for d in '${DTB_FILES}'.split())}'
UBOOT_MACHINE = "ni_neon_rev2_defconfig"

MACHINE_FEATURES:append:ni-neon-rev2 = " tpm"
