require ni-titanium.inc

UBOOT_MACHINE = "ni_x410_rev4_defconfig"

WKS_FILE ?= "ni-titanium-rev4.wks"
WKS_FILES ?= "${WKS_FILE}"

# include this after defining WKS_FILE
require conf/machine/ni-titanium-xlnx-${XILINX_XSCT_VERSION}.conf
