DISTRO_VERSION = "2025.00"
DISTRO_NAME = "Alchemy"
DISTRO_CODENAME = "Alchemy-Scarthgap"

# set to 1 to create software bill of material (SBOM) and 
# check for common vulnerabilities and exposures (CVEs)
ALCHEMY_CREATE_SBOM ?= "0"
ALCHEMY_CREATE_CVE_CHECK ?= "0"

CREATE_SPDX = "${@bb.utils.contains('ALCHEMY_CREATE_SBOM', '1', 'create-spdx', '', d)}"
CVE_CHECK = "${@bb.utils.contains('ALCHEMY_CREATE_CVE_CHECK', '1', 'cve-check', '', d)}"

DISTRO_FEATURES:append = " opengl x11 tpm usrmerge ${CREATE_SPDX}"

#Check for known CVEs (Common Vulnerabilities and Exposures)
INHERIT += " ${CREATE_SPDX} ${CVE_CHECK}"
# Filter out obsolete CVE database entries
# which are known not to impact software from Poky and OE-Core
# (only has effect if cve-check is enabled)
include cve-extra-exclusions.inc

PACKAGECONFIG:pn-gnuradio ?= "uhd zeromq"
PACKAGECONFIG:pn-gr-osmosdr ?= "uhd"
PACKAGECONFIG:pn-boost ?= "locale python"
PACKAGECONFIG:pn-grpc ?= "cpp shared python"
PACKAGECONFIG:pn-grpc-native ?= "cpp shared python"
PACKAGECONFIG:pn-protobuf ?= "compiler"

PACKAGECONFIG:pn-systemd:append = " networkd timedated timesyncd logind resolved hostnamed set-time-epoch"

PACKAGE_CLASSES ?= "package_ipk"

USER_CLASSES ?= "image-buildinfo"

DISTRO_FEATURES:append = " systemd"
DISTRO_FEATURES_BACKFILL_CONSIDERED = "sysvinit"

VIRTUAL-RUNTIME_init_manager = "systemd"
INIT_MANAGER = "systemd"

PREFERRED_UHD_VERSION ?= "4.10%"
PREFERRED_VERSION_uhd ?= "${PREFERRED_UHD_VERSION}"
PREFERRED_VERSION_uhd-fpga-images ?= "${PREFERRED_UHD_VERSION}"
PREFERRED_VERSION_mpmd ?= "${PREFERRED_UHD_VERSION}"

# Use glibc by default as musl in combination with systemd is not officilly
# supported by Openembedded
TCLIBC ?= "glibc"
OLDEST_KERNEL = "5.10"
