SRC_URI_append_ni-sulfur = " \
    file://sulfur/0001-i2c-muxes-pca954x-Add-support-for-GPIO-reset-line.patch \
    file://sulfur/0002-misc-cros_ec-Add-trivial-support-for-software-sync.patch \
    file://sulfur/0003-ni-zynq-Add-support-for-NI-Ettus-Research-Project-Su.patch \
    file://sulfur/0004-ni-zynq-Add-support-for-NI-Ettus-Research-Project-Su.patch \
    file://sulfur/0005-ni-sulfur-rev3-Added-swsync-feature.patch \
    file://sulfur/0001-ni-zynq-Add-support-for-Project-Phosphorus.patch \
    "


